//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transID { get; set; }
        public string transName { get; set; }
        public decimal value { get; set; }
        public System.DateTime date { get; set; }
        public bool isRecurring { get; set; }
        public Nullable<int> recurIntervalDays { get; set; }
        public int categoryID { get; set; }
        public int userID { get; set; }
        public Nullable<int> loanID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual User User { get; set; }
    }
}
