// <auto-generated />
using System;
using MVCTest2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCTest2.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCTest2.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "HR"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "Finance"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "IT"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "Marketing"
                        });
                });

            modelBuilder.Entity("MVCTest2.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentDeptId")
                        .HasColumnType("int");

                    b.Property<int>("Dept")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentDeptId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "NY",
                            Age = 33,
                            Dept = 1,
                            DeptId = 0,
                            Email = "sarah@company.com",
                            ImageName = "sarah.jpg",
                            Name = "Sarah",
                            Salary = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "AL",
                            Age = 29,
                            Dept = 3,
                            DeptId = 0,
                            Email = "michael@company.com",
                            ImageName = "michael.jpg",
                            Name = "Michael",
                            Salary = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "CA",
                            Age = 42,
                            Dept = 2,
                            DeptId = 0,
                            Email = "logan@company.com",
                            ImageName = "logan.jpg",
                            Name = "Logan",
                            Salary = 0.0
                        });
                });

            modelBuilder.Entity("MVCTest2.Models.Employee", b =>
                {
                    b.HasOne("MVCTest2.Models.Department", null)
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentDeptId");
                });

            modelBuilder.Entity("MVCTest2.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
